---
settings:
  name: NetApp container solutions
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: true
  pdf:
    gen-type: named-only
    zip-level: 1
    zip-filename: netapp-solutions-containers.zip
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Solutions de conteneurs
    url: "/index.html"
  - title: Quoi de neuf
    url: "/whats-new.html"
  - section: anthos
  - section: openshift
  - section: openshift-aws
  - title: Vidéos
    url: "/videos/index.html"
    entries:
    - title: Anthos
      url: "/videos/anthos-videos.html"
    - title: Red Hat OpenShift
      url: "/videos/openshift-videos.html"
  - title: Blogs
    url: "/blogs.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: NetApp solutions
  repo: netapp-solutions-family
