---
sidebar: sidebar 
permalink: vsphere-kubernetes-service/vks-overview.html 
keywords: vks, vSphere Kubernetes Service, ONTAP, kubernetes, overview 
summary: Découvrez le service Kubernetes vSphere et son intégration avec NetApp ONTAP pour les charges de travail conteneurisées. 
---
= Découvrez le service Kubernetes de VMware vSphere avec NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware vSphere Kubernetes Service (VKS) est une offre Kubernetes managée de VMware qui permet aux organisations de déployer, gérer et faire évoluer des applications conteneurisées à l'aide de Kubernetes. Associé au stockage NetApp ONTAP, VKS offre une persistance, des performances et une gestion des données de niveau entreprise pour les charges de travail cloud-native.

VKS est intégré à VMware Cloud Foundation (VCF) et conforme à la norme CNCF Kubernetes en amont, assurant ainsi la compatibilité avec l'écosystème Kubernetes plus large et les outils associés.



[[key-features-of-vsphere-kubernetes-service]]
== Principales caractéristiques du service Kubernetes vSphere

. *Clusters Kubernetes gérés :* vSphere Kubernetes Service simplifie le déploiement et la gestion des clusters Kubernetes. Il automatise des tâches telles que la création, la mise à niveau, le dimensionnement et la surveillance des clusters.
. *Intégration avec l'infrastructure VMware :* VKS s'intègre parfaitement à VMware vSphere, NSX-T et autres solutions VMware, permettant aux organisations de tirer parti de leur infrastructure VMware existante pour les charges de travail Kubernetes.
. *Prise en charge du multicloud et du cloud hybride :* vSphere Kubernetes Service prend en charge le déploiement sur des clouds privés, des clouds publics (par exemple, AWS, Azure, Google Cloud) et des environnements de cloud hybride, offrant ainsi aux organisations une flexibilité dans la gestion de leurs applications.
. *Sécurité intégrée :* VKS inclut des fonctionnalités de sécurité telles que le contrôle d'accès basé sur les rôles (RBAC), l’application de politiques et l’intégration avec VMware NSX pour la sécurité du réseau.
. *Prise en charge de l'écosystème Kubernetes :* VKS prend en charge l'intégralité de l'API Kubernetes en amont, garantissant ainsi la portabilité entre les environnements et la compatibilité avec l'écosystème Kubernetes au sens large, notamment avec des outils comme Istio pour le service mesh, Prometheus pour la supervision, et d'autres outils certifiés CNCF. Les organisations peuvent appliquer directement les compétences et intégrations Kubernetes standard aux clusters VKS.
. *Outils conviviaux pour les développeurs :* VKS prend en charge les flux de travail standard des développeurs Kubernetes, notamment les pipelines CI/CD, les pratiques GitOps et les outils comme kubectl et Helm, permettant aux équipes de développement de créer et de déployer des applications conteneurisées sans avoir à apprendre des interfaces propriétaires.
. *Évolutivité et haute disponibilité :* VKS offre des fonctionnalités telles que la mise à l’échelle automatique et la tolérance aux pannes pour garantir que les applications restent hautement disponibles et performantes.
. *Observabilité et surveillance :* VKS s’intègre aux outils de surveillance standard compatibles avec Kubernetes pour fournir des informations en temps réel sur la performance de l'application.




[[use-cases-for-vsphere-kubernetes-service]]
== Cas d'utilisation du service Kubernetes vSphere

. *Modernisation des applications :* Les organisations peuvent moderniser leurs applications existantes en les conteneurisant et en les déployant sur des clusters Kubernetes gérés par VKS.
. *DevOps Enablement :* VKS prend en charge les workflows DevOps en fournissant l'automatisation, l'intégration CI/CD et des outils adaptés aux développeurs.
. *Déploiements de cloud hybride :* Les entreprises peuvent utiliser VKS pour déployer des clusters Kubernetes dans des environnements sur site et cloud, permettant ainsi des opérations cohérentes.
. *Architecture de microservices :* VKS prend en charge le développement d'applications basé sur les microservices, permettant aux équipes de construire et de faire évoluer des systèmes distribués.

