---
sidebar: sidebar 
permalink: vsphere-kubernetes-service/vks-overview.html 
keywords: vks, vSphere Kubernetes Service, ONTAP, kubernetes, overview 
summary: Découvrez le service Kubernetes vSphere et son intégration avec NetApp ONTAP pour les charges de travail conteneurisées. 
---
= Découvrez le service Kubernetes vSphere avec NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
vSphere Kubernetes Service (VKS) est une offre Kubernetes managée de VMware qui permet aux entreprises de déployer, gérer et faire évoluer des applications conteneurisées à l'aide de Kubernetes. Associé au stockage NetApp ONTAP, VKS offre une persistance, des performances et une gestion des données de niveau entreprise pour les charges de travail cloud natives.

vSphere Kubernetes Service est généralement intégré dans l'écosystème plus large de VMware, tel que VMware Tanzu, qui fournit une suite complète d'outils pour la gestion de Kubernetes, la modernisation des applications et les pratiques DevOps.



[[key-features-of-vsphere-kubernetes-service]]
== Principales caractéristiques du service Kubernetes vSphere

. *Clusters Kubernetes gérés :* vSphere Kubernetes Service simplifie le déploiement et la gestion des clusters Kubernetes. Il automatise des tâches telles que la création, la mise à niveau, le dimensionnement et la surveillance des clusters.
. *Intégration avec l'infrastructure VMware :* VKS s'intègre parfaitement à VMware vSphere, NSX-T et autres solutions VMware, permettant aux organisations de tirer parti de leur infrastructure VMware existante pour les charges de travail Kubernetes.
. *Prise en charge du multicloud et du cloud hybride :* vSphere Kubernetes Service prend en charge le déploiement sur des clouds privés, des clouds publics (par exemple, AWS, Azure, Google Cloud) et des environnements de cloud hybride, offrant ainsi aux organisations une flexibilité dans la gestion de leurs applications.
. *Sécurité intégrée :* VKS inclut des fonctionnalités de sécurité telles que le contrôle d'accès basé sur les rôles (RBAC), l’application de politiques et l’intégration avec VMware NSX pour la sécurité du réseau.
. *Outils conviviaux pour les développeurs :* vSphere Kubernetes Service s’intègre à des outils de développement comme Tanzu Application Platform pour simplifier le développement et le déploiement d’applications conteneurisées.
. *Évolutivité et haute disponibilité :* VKS offre des fonctionnalités telles que la mise à l’échelle automatique et la tolérance aux pannes pour garantir que les applications restent hautement disponibles et performantes.
. *Observabilité et surveillance :* vSphere Kubernetes Service s’intègre à VMware Tanzu Observability (anciennement Wavefront) et à d’autres outils de surveillance pour fournir des informations en temps réel sur la performance de l'application et du cluster.
. *Prise en charge de l'écosystème Kubernetes :* VKS est entièrement conforme à la version amont de Kubernetes, ce qui signifie qu'il prend en charge l'API Kubernetes et fonctionne avec les outils natifs de Kubernetes tels que Helm, Istio et Prometheus.




[[use-cases-for-vsphere-kubernetes-service]]
== Cas d'utilisation du service Kubernetes vSphere

. *Modernisation des applications :* Les organisations peuvent moderniser leurs applications existantes en les conteneurisant et en les déployant sur des clusters Kubernetes gérés par VKS.
. *DevOps Enablement :* VKS prend en charge les workflows DevOps en fournissant l'automatisation, l'intégration CI/CD et des outils adaptés aux développeurs.
. *Déploiements de cloud hybride :* Les entreprises peuvent utiliser VKS pour déployer des clusters Kubernetes dans des environnements sur site et cloud, permettant ainsi des opérations cohérentes.
. *Architecture de microservices :* VKS prend en charge le développement d'applications basé sur les microservices, permettant aux équipes de construire et de faire évoluer des systèmes distribués.

