---
sidebar: sidebar 
permalink: anthos/anthos-solution-overview.html 
keywords: NVA-1165, Anthos, GKE, Netapp, Trident 
summary: 'Ce document de référence fournit la validation du déploiement de la solution Anthos avec NetApp , déployée dans plusieurs environnements de centres de données, comme validé par NetApp et nos partenaires d"ingénierie.' 
---
= NVA-1165 : Anthos avec NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Banu Sundhar et Suresh Thoppay, NetApp

[role="lead"]
Ce document de référence fournit la validation du déploiement de la solution Anthos avec NetApp par NetApp et nos partenaires d'ingénierie lorsqu'elle est déployée dans plusieurs environnements de centres de données.  Il détaille également l'intégration du stockage avec les systèmes de stockage NetApp en utilisant l'orchestrateur de stockage Trident pour la gestion du stockage persistant.  Enfin, nous explorons et documentons un certain nombre de validations de solutions et de cas d’utilisation réels.



== Cas d'utilisation

La solution Anthos avec NetApp est conçue pour offrir une valeur exceptionnelle aux clients avec les cas d'utilisation suivants :

* Environnement Anthos facile à déployer et à gérer déployé à l'aide du `bmctl` outil sur métal nu ou le `gkectl` outil sur VMware vSphere.
* Puissance combinée du conteneur d'entreprise et des charges de travail virtualisées avec Anthos déployées virtuellement sur vSphere ou sur du bare metal avec https://cloud.google.com/anthos/clusters/docs/bare-metal/1.9/how-to/vm-workloads["kubevirt"^] .
* Configuration et cas d'utilisation réels mettant en évidence les fonctionnalités d'Anthos lorsqu'elles sont utilisées avec le stockage NetApp et Trident, l'orchestrateur de stockage open source pour Kubernetes.




== Valeur commerciale

Les entreprises adoptent de plus en plus les pratiques DevOps pour créer de nouveaux produits, raccourcir les cycles de publication et ajouter rapidement de nouvelles fonctionnalités.  En raison de leur nature agile innée, les conteneurs et les microservices jouent un rôle crucial dans le soutien des pratiques DevOps.  Cependant, la pratique de DevOps à l’échelle de la production dans un environnement d’entreprise présente ses propres défis et impose certaines exigences à l’infrastructure sous-jacente, telles que les suivantes :

* Haute disponibilité à toutes les couches de la pile
* Facilité des procédures de déploiement
* Opérations et mises à niveau non perturbatrices
* Infrastructure pilotée par API et programmable pour suivre l'agilité des microservices
* Multilocation avec garanties de performance
* La capacité d'exécuter simultanément des charges de travail virtualisées et conteneurisées
* La capacité de faire évoluer l'infrastructure de manière indépendante en fonction des demandes de charge de travail


La solution Anthos avec NetApp reconnaît ces défis et présente une solution qui permet de répondre à chaque préoccupation en mettant en œuvre le déploiement entièrement automatisé d'Anthos sur site dans l'environnement de centre de données choisi par le client.



== Aperçu de la technologie

La solution Anthos avec NetApp comprend les principaux composants suivants :



=== Anthos sur site

Anthos On Prem est une plateforme Kubernetes d'entreprise entièrement prise en charge qui peut être déployée dans l'hyperviseur VMware vSphere ou sur une infrastructure bare metal de votre choix.

Pour plus d'informations sur Anthos, consultez le site Web d'Anthos situé https://cloud.google.com/anthos["ici"^] .



=== Systèmes de stockage NetApp

NetApp dispose de plusieurs systèmes de stockage parfaits pour les centres de données d’entreprise et les déploiements de cloud hybride.  Le portefeuille NetApp comprend NetApp ONTAP, Cloud Volumes ONTAP, Google Cloud NetApp Volumes, Azure NetApp Files, FSx ONTAP pour les systèmes de stockage NetApp ONTAP , qui peuvent tous fournir un stockage persistant pour les applications conteneurisées.

Pour plus d'informations, visitez le site Web de NetApp https://www.netapp.com["ici"] .



=== Intégrations de stockage NetApp

Trident est un orchestrateur de stockage open source et entièrement pris en charge pour les conteneurs et les distributions Kubernetes, y compris Anthos.

Pour plus d'informations, visitez le site Web de Trident https://docs.netapp.com/us-en/trident/index.html["ici"] .



== Options de configuration avancées

Cette section est dédiée aux personnalisations que les utilisateurs réels devront probablement effectuer lors du déploiement de cette solution en production, comme la création d'un registre d'images privé dédié ou le déploiement d'instances d'équilibreur de charge personnalisées.



== Matrice de support actuelle pour les versions validées

Voir https://cloud.google.com/anthos/docs/resources/partner-storage#netapp["ici"] pour la matrice de support des versions validées.
