---
sidebar: sidebar 
permalink: anthos/anthos-metallb.html 
summary: 'Cette page détaille les instructions d"installation et de configuration de l"équilibreur de charge MetalLB.' 
keywords: Anthos, Kubernetes, MetalLB, LoadBalancer, 
---
= Installation des équilibreurs de charge MetalLB
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette page répertorie les instructions d'installation et de configuration de l'équilibreur de charge géré MetalLB.



== Installation de l'équilibreur de charge MetalLB

L'équilibreur de charge MetalLB est entièrement intégré à Anthos Clusters sur VMware et dispose d'un déploiement automatisé effectué dans le cadre des configurations de cluster administrateur et utilisateur à partir de la version 1.11.  Il y a des blocs de texte dans les `cluster.yaml` fichiers de configuration que vous devez modifier pour fournir des informations sur l'équilibreur de charge.  Il est auto-hébergé sur votre cluster Anthos au lieu de nécessiter le déploiement de ressources externes comme les autres solutions d'équilibrage de charge prises en charge.  Il permet également de créer un pool IP qui attribue automatiquement des adresses avec la création de services Kubernetes de type load balancer dans des clusters qui ne s'exécutent pas sur un fournisseur cloud.



== Intégration avec Anthos

Lors de l'activation de l'équilibreur de charge MetalLB pour l'administrateur Anthos, vous devez modifier quelques lignes dans le `loadBalancer:` section qui existe dans le `admin-cluster.yaml` déposer.  Les seules valeurs que vous devez modifier sont celles pour définir le `controlPlaneVIP:` adresse, puis définissez le `kind:` comme MetalLB.  Consultez l’extrait de code suivant pour un exemple :

[listing]
----
# (Required) Load balancer configuration
loadBalancer:
  # (Required) The VIPs to use for load balancing
  vips:
    # Used to connect to the Kubernetes API
    controlPlaneVIP: "10.61.181.230"
    # # (Optional) Used for admin cluster addons (needed for multi cluster features). Must
    # # be the same across clusters
    # addonsVIP: ""
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" "ManualLB" or "MetalLB".
  # Uncomment the corresponding field below to provide the detailed spec
  kind: MetalLB
----
Lors de l'activation de l'équilibreur de charge MetalLB pour les clusters d'utilisateurs Anthos, il existe deux zones dans chaque `user-cluster.yaml` fichier que vous devez mettre à jour.  Tout d’abord, d’une manière similaire à la `admin-cluster.yaml` fichier, vous devez modifier le `controlPlaneVIP:` , `ingressVIP:` , et `kind:` valeurs dans le `loadBalancer:` section.  Voir l’extrait de code suivant pour un exemple :

[listing]
----
loadBalancer:
  # (Required) The VIPs to use for load balancing
  vips:
    # Used to connect to the Kubernetes API
    controlPlaneVIP: "10.61.181.240"
    # Shared by all services for ingress traffic
    ingressVIP: "10.61.181.244"
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" "ManualLB" or "MetalLB".
  # Uncomment the corresponding field below to provide the detailed spec
  kind: MetalLB
----

NOTE: L'adresse IP ingressVIP doit exister dans le pool d'adresses IP attribuées à l'équilibreur de charge MetalLB ultérieurement dans la configuration.

Vous devez ensuite naviguer vers le `metalLB:` sous-section et modifier le `addressPools:` section en nommant la piscine dans le `- name:` variable.  Vous devez également créer un pool d'adresses IP que MetalLB peut attribuer aux services de type LoadBalancer en fournissant une plage au `addresses:` variable.

[listing]
----
# # (Required when using "MetalLB" kind in user clusters) Specify the MetalLB config
 metalLB:
 #   # (Required) A list of non-overlapping IP pools used by load balancer typed services.
 #   # Must include ingressVIP of the cluster.
    addressPools:
 #   # (Required) Name of the address pool
    - name: "default"
 #     # (Required) The addresses that are part of this pool. Each address must be either
 #     # in the CIDR form (1.2.3.0/24) or range form (1.2.3.1-1.2.3.5).
      addresses:
      - "10.61.181.244-10.61.181.249"
----

NOTE: Le pool d'adresses peut être fourni sous forme de plage comme dans l'exemple, en le limitant à un certain nombre d'adresses dans un sous-réseau particulier, ou il peut être fourni sous forme de notation CIDR si l'ensemble du sous-réseau est rendu disponible.

. Lorsque des services Kubernetes de type LoadBalancer sont créés, MetalLB attribue automatiquement une adresse IP externe aux services et annonce l'adresse IP en répondant aux requêtes ARP.

