---
sidebar: sidebar 
permalink: videos/tanzu-videos.html 
keywords: video, demonstration, deployment, VMware Tanzu with NetApp, NetApp, Tanzu 
summary: Cette page contient des liens vers des vidéos qui démontrent certaines des fonctionnalités décrites dans ce document. 
---
= Regardez des vidéos sur VMware Tanzu avec NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Découvrez l'intégration de VMware Tanzu avec NetApp à travers une série de vidéos démontrant des fonctionnalités clés telles que le provisionnement de stockage persistant, le clonage d'applications et la protection des données à l'aide de Trident.


NOTE: Ces démos ont été enregistrées en tant qu'aperçu technique en utilisant la version 1.3.1 de TKG et la version 21.12 de Trident Protect.  Veuillez consulter la matrice de support pour les versions officielles prises en charge.



== Provisionnement de stockage persistant

.Utiliser Trident pour provisionner le stockage persistant dans VMware Tanzu - VMware Tanzu avec NetApp
video::8db3092b-3468-4754-b2d7-b01200fbb38d[panopto,width=360]


== Clonage d'applications et protection des données

.Utiliser Trident Protect pour cloner des applications dans VMWare Tanzu - VMware Tanzu avec NetApp
video::01aff358-a0a2-4c4f-9062-b01200fb9abd[panopto,width=360]