---
sidebar: sidebar 
permalink: openshift/os-trident-element-iscsi.html 
summary:  
keywords: Trident, Element, Solidfire, iSCSI 
---
= Configuration iSCSI de NetApp Element
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour activer l'intégration de Trident avec le système de stockage NetApp Element , vous devez créer un backend qui permet la communication avec le système de stockage à l'aide du protocole iSCSI.

. Des exemples de fichiers backend sont disponibles dans l'archive d'installation téléchargée dans le `sample-input` hiérarchie des dossiers.  Pour les systèmes NetApp Element servant iSCSI, copiez le `backend-solidfire.json` fichier dans votre répertoire de travail et modifiez le fichier.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/backends-samples/solidfire/backend-solidfire.json ./
[netapp-user@rhel7 trident-installer]$ vi ./backend-solidfire.json
----
+
.. Modifiez l'utilisateur, le mot de passe et la valeur MVIP sur le `EndPoint` doubler.
.. Modifier le `SVIP` valeur.
+
[listing]
----
 {
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://trident:password@172.21.224.150/json-rpc/8.0",
    "SVIP": "10.61.180.200:3260",
    "TenantName": "trident",
    "Types": [{"Type": "Bronze", "Qos": {"minIOPS": 1000, "maxIOPS": 2000, "burstIOPS": 4000}},
              {"Type": "Silver", "Qos": {"minIOPS": 4000, "maxIOPS": 6000, "burstIOPS": 8000}},
              {"Type": "Gold", "Qos": {"minIOPS": 6000, "maxIOPS": 8000, "burstIOPS": 10000}}]
}
----


. Avec ce fichier back-end en place, exécutez la commande suivante pour créer votre premier back-end.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ ./tridentctl -n trident create backend -f backend-solidfire.json
+-------------------------+----------------+--------------------------------------+--------+---------+
|          NAME           | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------------------+----------------+--------------------------------------+--------+---------+
| solidfire_10.61.180.200 | solidfire-san  | b90783ee-e0c9-49af-8d26-3ea87ce2efdf | online |       0 |
+-------------------------+----------------+--------------------------------------+--------+---------+
----
. Une fois le backend créé, vous devez ensuite créer une classe de stockage.  Tout comme pour le backend, il existe un exemple de fichier de classe de stockage qui peut être modifié pour l'environnement disponible dans le dossier sample-inputs.  Copiez-le dans le répertoire de travail et apportez les modifications nécessaires pour refléter le backend créé.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/storage-class-samples/storage-class-csi.yaml.templ ./storage-class-basic.yaml
[netapp-user@rhel7 trident-installer]$ vi storage-class-basic.yaml
----
. La seule modification qui doit être apportée à ce fichier est de définir le `backendType` valeur au nom du pilote de stockage du backend nouvellement créé.  Notez également la valeur du champ de nom, qui doit être référencée dans une étape ultérieure.
+
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "solidfire-san"
----
+

NOTE: Il existe un champ facultatif appelé `fsType` qui est défini dans ce fichier.  Dans les backends iSCSI, cette valeur peut être définie sur un type de système de fichiers Linux spécifique (XFS, ext4, etc.), ou elle peut être supprimée pour permettre à OpenShift de décider quel système de fichiers utiliser.

. Exécutez le `oc` commande pour créer la classe de stockage.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ oc create -f storage-class-basic.yaml
storageclass.storage.k8s.io/basic-csi created
----
. Une fois la classe de stockage créée, vous devez ensuite créer la première revendication de volume persistant (PVC).  Il y a un échantillon `pvc-basic.yaml` fichier qui peut être utilisé pour effectuer cette action situé également dans sample-inputs.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/pvc-samples/pvc-basic.yaml ./
[netapp-user@rhel7 trident-installer]$ vi pvc-basic.yaml
----
. La seule modification qui doit être apportée à ce fichier est de s'assurer que le `storageClassName` le champ correspond à celui qui vient d'être créé.  La définition du PVC peut être davantage personnalisée selon les besoins de la charge de travail à provisionner.
+
[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
. Créez le PVC en émettant le `oc` commande.  La création peut prendre un certain temps en fonction de la taille du volume de support en cours de création, vous pouvez donc observer le processus au fur et à mesure de son exécution.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ oc create -f pvc-basic.yaml
persistentvolumeclaim/basic created

[netapp-user@rhel7 trident-installer]$ oc get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
basic   Bound    pvc-3445b5cc-df24-453d-a1e6-b484e874349d   1Gi        RWO            basic-csi      5s
----

